services:
  - type: web
    name: smartprof
    runtime: python
    plan: free
    buildCommand: pip install -r server/requirements.txt
    startCommand: cd server && python seed/seed_all.py && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
